web1:
  before_deploy:
  # Download media images from github repo & extract
  - "tar -xz < <(curl -s http://cloud.github.com/downloads/pagodabox/magento-install/magento-media.tar.gz)"
  # Import sample catalog sql file
  - "php /var/www/pagoda/magento_sample_data.php"
  - "mysql -h $DB1_HOST --port $DB1_PORT -u $DB1_USER -p$DB1_PASS $DB1_NAME < /tmp/magento_sample_data_processed.sql"
  - "php /var/www/index.php > /dev/null"
  # Increase php execution time to accomidate db import & migrations
  php_max_execution_time: 300